name: java_book_binder
channels:
  - conda-forge
  - defaults
dependencies:
  # Python environment
  - python=3.11
  - ipython
  - jupyterlab
  - thebe
  - openjdk
  - pip
  - pip:
      - jjava

  # Java environment
